# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-12-13 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20201213_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasestatusmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchasestatusmodel',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaseModel', to='purchase.PurchaseModel'),
        ),
    ]
